#!/bin/sh
#
# qseecomd        init.d script to start the securemsm qseecomd daemon
#
#

set -e

soc_id=`cat /sys/devices/soc0/soc_id`

#if [[ "$soc_id" -ne "290" && "$soc_id" -ne "296" && "$soc_id" -ne "297" && "$soc_id" -ne "298" ]]; then
if [[ "$soc_id" -ne "290" && "$soc_id" -ne "296" && "$soc_id" -ne "298" ]]; then
    case "$1" in
      start)
            echo -n "Starting securemsm qseecomd daemon...: " > /dev/kmsg

            chmod o+rw /dev/qseecom /dev/ion

            if [ -e /dev/sde20 ]; then
                chmod 0664 /dev/sde20
            fi
            start-stop-daemon -S -b -a /usr/bin/qseecomd
            echo "done" > /dev/kmsg
            ;;
      stop)
            echo -n "Stoping securemsm qseecomd daemon......: " > /dev/kmsg
            start-stop-daemon -K -n qseecomd
            echo "done" > /dev/kmsg
            ;;
      restart)
            $0 stop
            $0 start
            ;;
      *)
            echo "Usage qseecomd { start | stop | restart}" >&2
            exit 1
            ;;
    esac
fi

exit 0
